### ISSUE TITLE
need php 8

### ISSUE THREAD

**Issue by maximsustavov** [lee-to/laravel-check-your-skill-test#4]
Problem 1
    - Installation request for psr/log 2.0.0 -> satisfiable by psr/log[2.0.0].
    - psr/log 2.0.0 requires php >=8.0.0 -> your PHP version (7.4.14) does not satisfy that requirement.
  Problem 2
    - psr/log 2.0.0 requires php >=8.0.0 -> your PHP version (7.4.14) does not satisfy that requirement.
    - filp/whoops 2.14.4 requires psr/log ^1.0.1 || ^2.0 || ^3.0 -> satisfiable by psr/log[2.0.0].
    - Installation request for filp/whoops 2.14.4 -> satisfiable by filp/whoops[2.14.4].

**Comment by lee-to** [comment]
Исправил! проблема была в том что забыл удалить composer.lock
