### ISSUE TITLE
Уточнения

### ISSUE THREAD

**Issue by AndreyBelozertsev** [lee-to/laravel-check-your-skill-test#6]
Тест по миграциям, задания не трудные, для новичка самое то, единственное долго разбирался какое задание к какой таблице относится, пришлось залезть в файлы теста и смотреть результаты проверки. И в задании 7 Blade шаблонизатора #### Задание 7: ForEach
`resources/views/table.blade.php`
Здесь сделайте классический foreach loop
- Выведите div с $user->name
- Воспользуйтесь переменной $loop и у нечетных div выведите класс - `bg-red-500`

Почему-то так и не получилось выполнить условие теста по добавлению класса для нечетных див-ов.
Код при создании сидов и выводе на страницу отрабатывает так как надо.    
@foreach($data as $user)
        <div @if($loop->odd) class="bg-red-500"  @endif > {{ $user->name }} </div>
   @endforeach

Так и не понял, почему результат теста не пройден. 

А так большое спасибо, освежил старое и взял на вооружение новые вещи!!!!

**Comment by lee-to** [comment]
Внес правку в этот тест, сделайте pull request с последними обновленями в ветке и тесты пройдут
